Default: &defaults
  database: testyesod.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: testyesod_test.sqlite3
  <<: *defaults

Staging:
  database: testyesod_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: testyesod_production.sqlite3
  poolsize: 100
  <<: *defaults
